openapi: 3.0.0
info:
  title: Dashboard API
  version: '1.0'
  description: 'API '
  contact:
    name: Duc PX
    email: ducphamxuan@vccorp.vn
servers:
  - url: 'https://dev.bizflycloud.vn/api/cloud-backup'
paths:
  /dashboard/machines:
    get:
      summary: Lấy tất cả machines của tenant
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/MachineGet.v1.yaml
              examples:
                machines:
                  value:
                    - agent_version: '0.01'
                      created_at: 'Wed, 10 Jun 2020 15:14:47 GMT'
                      'host_name ': mysql-server
                      id: 743d916d-1362-4328-a1d4-c53ccd1bd625
                      ip_address: 10.0.0.1
                      name: mysql
                      os_version: windows
                      'tenant_id ': 98dbba57-60c7-4c22-8087-8313997ea776
                      updated_at: 'Wed, 10 Jun 2020 15:14:47 GMT'
                    - agent_version: null
                      created_at: 'Wed, 10 Jun 2020 16:30:56 GMT'
                      'host_name ': null
                      id: 3e213039-41c7-4c10-9dc0-1a8dc0bf4823
                      ip_address: null
                      name: null
                      os_version: null
                      'tenant_id ': 98dbba57-60c7-4c22-8087-8313997ea776
                      updated_at: 'Wed, 10 Jun 2020 16:30:56 GMT'
      operationId: get all machines
      tags:
        - Machines
    post:
      summary: Tạo mới một Machine
      operationId: post-machines
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: ../models/MachinePost.v1.yaml
              examples:
                machine-1:
                  value:
                    access_key: UBZ6YHKFHWKCADINEGPQ
                    agent_version: '0.1'
                    created_at: 'Thu, 11 Jun 2020 09:17:51 GMT'
                    'host_name ': host name
                    id: 8d8ead54-0d81-45e2-bd03-0b94cde42cc0
                    ip_address: 10.10.10.25
                    name: machine name
                    os_version: windows 10
                    secret_key: 19d2b170ae550eb2697ff0b2f0e9aaedcab564080eee8e9c3e335bd749bea621
                    os_machine_id: null
                    encryption: false
                    'tenant_id ': 98dbba57-60c7-4c22-8087-8313997ea776
                    updated_at: 'Thu, 11 Jun 2020 09:17:51 GMT'
                    file_content:
                      access_key: RZVA6JIAF7JNH3KENRFE
                      api_url: config
                      broker_url: config
                      machine_id: 96eb548c-42b3-4fe9-a873-8658769dc293
                      secret_key: b57b476c1ef401cfb90e598580efea9c33b37a2ee6f765e9bddf5aa395461387
                machine2:
                  value:
                    access_key: UBZ6YHKFHWKCADINEGPQ
                    agent_version: null
                    created_at: 'Thu, 11 Jun 2020 09:17:51 GMT'
                    'host_name ': null
                    id: 8d8ead54-0d81-45e2-bd03-0b94cde42cc0
                    ip_address: null
                    name: null
                    os_version: null
                    secret_key: 19d2b170ae550eb2697ff0b2f0e9aaedcab564080eee8e9c3e335bd749bea621
                    os_machine_id: null
                    encryption: false
                    'tenant_id ': 98dbba57-60c7-4c22-8087-8313997ea776
                    updated_at: 'Thu, 11 Jun 2020 09:17:51 GMT'
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/MachineRequest.v1.yaml
            examples:
              machine-1:
                value:
                  name: machine name
                  host_name: host name
                  ip_address: 10.10.10.25
                  os_version: windows 10
                  agent_version: '0.1'
          application/xml:
            schema:
              $ref: ../models/Machine.v1.yaml
        description: Optional
      parameters: []
      description: ''
      tags:
        - Machines
    parameters: []
  '/dashboard/machines/{machine_id}':
    get:
      summary: Show machine details
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/MachineGet.v1.yaml
              examples:
                example-1:
                  value:
                    agent_version: '0.01'
                    created_at: 'Tue, 02 Jun 2020 09:43:15 GMT'
                    'host_name ': mysql-server
                    id: 08157574-7428-4494-b1ee-857e1767acdd
                    ip_address: 10.0.0.1
                    name: mysql
                    os_version: windows
                    'tenant_id ': 98dbba57-60c7-4c22-8087-8313997ea776
                    updated_at: 'Tue, 02 Jun 2020 09:43:15 GMT'
      operationId: get-machines-machine_id
      tags:
        - Machines
    parameters:
      - schema:
          type: string
        name: machine_id
        in: path
        required: true
    patch:
      summary: Update machine
      operationId: patch-machines-machine_id
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/MachineGet.v1.yaml
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/MachineRequest.v1.yaml
            examples:
              patch-machine:
                value:
                  name: Nginx Server
                  host_name: nginx-1
                  ip_address: 10.3.35.12
                  os_version: linux
                  agent_version: '0.1'
      tags:
        - Machines
    delete:
      summary: Xóa machine
      operationId: delete-machines-machine_id
      responses:
        '200':
          description: OK
      description: "Xóa Machine có 2 option:\n- Xóa Machine kèm theo xóa toàn bộ data của machine (default)\n- Xóa Machine nhưng giữ lại data. User sẽ phải xóa những data này bằng tay trên dashboard\n\nRequest body to delete directory:\n```\n{\n\t\"keep\": True/False\n\t\"directory_ids\": [list directory id]\n}\n```\n\nKeep: True cho phép giữ lại các bản data, False sẽ xóa hết data\nnếu Keep True thì truyền thêm danh sách directory được giữ lại data"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                directory_ids:
                  type: array
                  items:
                    type: string
                    format: uuid
              required:
                - directory_ids
      tags:
        - Machines
  '/dashboard/machines/{machine_id}/directories':
    parameters:
      - schema:
          type: string
        name: machine_id
        in: path
        required: true
    get:
      summary: Lấy danh sách Backup Directory theo machine_id
      tags:
        - BackupDirectory
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/BackupDirectory.v1.yaml
      operationId: get-reference-Dashboard-API.v1.yaml-paths-~1machines~1-machine_id-directories
    post:
      summary: Tạo một Backup Directory
      operationId: post-machines-machine_id-directories
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: ../models/BackupDirectory.v1.yaml
              examples:
                example-1:
                  value:
                    created_at: '2020-06-16T15:14:50.875699'
                    description: null
                    id: e0a69ae7-fada-4426-beca-704f67e6d46c
                    machine_id: e5e0c123-f7f8-425d-bb31-bc514c6e48ef
                    name: backup web
                    path: var/www/html
                    quota: null
                    size: 0
                    tenant_id: 98dbba57-60c7-4c22-8087-8313997ea776
                    updated_at: '2020-06-16T15:1'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/BackupDirectoryCreating.v1.yaml
            examples: {}
        description: 'request body phải có `path`, path là đường dẫn của thư mục cần backup. Một tên thư mục hợp lệ chỉ chứa các ký tự cho phép: `^[A-Za-z0-9/._-]*$`. Nếu path không hợp lệ thì trả về 400.'
      description: Tạo một Backup Directory thuộc machine_id
      tags:
        - BackupDirectory
  '/dashboard/machines/{machine_id}/directories/{backup_directory_id}':
    parameters:
      - schema:
          type: string
        name: machine_id
        in: path
        required: true
      - schema:
          type: string
        name: backup_directory_id
        in: path
        required: true
    get:
      summary: Lấy thông tin chi tiết của Backup Directory theo id
      tags:
        - BackupDirectory
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/BackupDirectory.v1.yaml
              examples:
                example-1:
                  value:
                    created_at: '2020-06-16T15:14:50.875699'
                    description: null
                    id: e0a69ae7-fada-4426-beca-704f67e6d46c
                    machine_id: e5e0c123-f7f8-425d-bb31-bc514c6e48ef
                    name: backup web
                    path: var/www/html
                    quota: null
                    size: 0
                    tenant_id: 98dbba57-60c7-4c22-8087-8313997ea776
                    updated_at: '2020-06-16T15:1'
      operationId: get-machines-machine_id-directories-backup_directory_id
    patch:
      summary: Update thông tin của Backup Directory
      operationId: patch-machines-machine_id-directories-backup_directory_id
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/BackupDirectory.v1.yaml
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                policies:
                  type: array
                  description: list policy id to apply to directory
                  items:
                    type: string
                    format: uuid
        description: |-
          Cho phép update thông tin về tên, thông tin mô tả, thêm/bỏ policies cho thư mục.
          policies là danh sách id của policies sẽ được apply cho thư mục sau khi update

          nếu không truyền policies tương đương với policies truyền list rỗng, khi đó các policies đang apply sẽ bị unapply toàn bộ

          ```
          {
              "name": "Backup mysql"
          }
          ```
      description: ''
      tags:
        - BackupDirectory
    delete:
      summary: Xóa Backup Directory theo id
      operationId: delete-machines-machine_id-directories-backup_directory_id
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '404':
          description: Not Found
      description: "Xóa Backup Directory có 2 option:\n- Xóa Backup Directory kèm theo xóa toàn bộ data của directory (default)\n- Xóa Backup Directory nhưng giữ lại data. User sẽ phải xóa những data này bằng tay trên dashboard\n\nRequest body to delete directory:\n```\n{\n\t\"keep\": True/False\n}\n```\n\nKeep: True cho phép giữ lại các bản data, False sẽ xóa hết data\n"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                keep:
                  type: boolean
              required:
                - keep
      tags:
        - BackupDirectory
  '/dashboard/machines/{machine_id}/directories/{backup_directory_id}/policies':
    parameters:
      - schema:
          type: string
        name: machine_id
        in: path
        required: true
      - schema:
          type: string
        name: backup_directory_id
        in: path
        required: true
    get:
      summary: Lấy danh sách các policy đang apply cho Backup Directory
      tags:
        - Backup Policy
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/Policy.v1.yaml
              examples:
                example-1:
                  value:
                    - created_at: '2020-06-13T11:48:12.554686'
                      id: c56b623c-385a-4a9d-834f-7364ffaf00ac
                      name: full backup
                      retention_days: null
                      retention_months: null
                      retention_weeks: null
                      schedule_pattern: '* * * *'
                      tenant_id: 98dbba57-60c7-4c22-8087-8313997ea776
                      updated_at: '2020-06-16T15:2'
      operationId: get-machines-machine_id-directories-backup_directory_id-policies
  /dashboard/backup-directories:
    get:
      summary: Lấy danh sách Backup Directory của tenant
      tags:
        - BackupDirectory
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/Policy.v1.yaml
              examples:
                example-1:
                  value:
                    - created_at: '2020-06-16T11:53:36.864994'
                      description: null
                      id: 3237174f-9a9b-4304-a72e-4ebdaa15b6a2
                      machine_id: e5e0c123-f7f8-425d-bb31-bc514c6e48ef
                      name: backup config
                      path: etc/nginx
                      quota: null
                      size: 0
                      tenant_id: 98dbba57-60c7-4c22-8087-8313997ea776
                      updated_at: '2020-06-16T11:5'
                    - created_at: '2020-06-16T15:14:50.875699'
                      description: null
                      id: e0a69ae7-fada-4426-beca-704f67e6d46c
                      machine_id: e5e0c123-f7f8-425d-bb31-bc514c6e48ef
                      name: backup web
                      path: etc/httpd
                      quota: null
                      size: 0
                      tenant_id: 98dbba57-60c7-4c22-8087-8313997ea776
                      updated_at: '2020-06-16T15:1'
      operationId: get-backup-directories
    parameters: []
  /dashboard/policies:
    get:
      summary: Lấy các policy của tenant
      tags:
        - Backup Policy
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/Policy.v1.yaml
      operationId: get-policies
    post:
      summary: Tạo mới một policy
      operationId: post-policies
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: ../models/Policy.v1.yaml
              examples:
                example-1:
                  value:
                    created_at: '2020-06-16T16:06:43.150717'
                    id: e58f7296-2e56-4fba-b511-3a3af3e006df
                    name: null
                    retention_days: 7
                    schedule_pattern: '* * * * *'
                    tenant_id: 98dbba57-60c7-4c22-8087-8313997ea776
                    updated_at: '2020-06-16T16:0'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
            examples: {}
        description: |-
          Hệ thống storage sẽ có một số loại khác nhau. Mỗi policy sẽ được gán vào một loại storage cụ thể (s3, tape). Nếu volume (vùng lưu trữ cho user) của loại storage đó chưa tạo cho user thì sẽ phải tạo mới. Với mỗi loại storage, một user chỉ được cấp duy nhất một volume.

          Request body: bắt buộc phải có `schedule_pattern` (định dạng tương tự crontab) để lập lịch thực hiện backup và `volume_type` để chỉ định loại lưu trữ.

          Các trường trong request body:
          - name
          - storage_type: S3
          - schedule_pattern
          - retention_days
          - description

          {
            "storage_type": "S3",
            "name": "backup dayly",
            "schedule_pattern": "* * * *"
          }
      tags:
        - Backup Policy
    parameters: []
  '/dashboard/policies/{policy_id}':
    parameters:
      - schema:
          type: string
        name: policy_id
        in: path
        required: true
    get:
      summary: Lấy thông tin chi tiết policy
      tags:
        - Backup Policy
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Policy.v1.yaml
        '404':
          description: Not Found
      operationId: get-policies-policy_id
    patch:
      summary: Update thông tin policy
      operationId: patch-policies-policy_id
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Policy.v1.yaml
              examples:
                example-1:
                  value:
                    created_at: '2020-06-16T16:06:43.150717'
                    id: e58f7296-2e56-4fba-b511-3a3af3e006df
                    name: backu weeken
                    retention_days: null
                    retention_months: null
                    retention_weeks: null
                    schedule_pattern: '* * * * *'
                    tenant_id: 98dbba57-60c7-4c22-8087-8313997ea776
                    updated_at: '2020-06-16T16:0'
        '400':
          description: Bad Request
        '404':
          description: Not Found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
        description: |
          Các thông tin được update:
          - name
          - schedule_pattern
          - retention_days

          ```
          {
            "name": "backup weeken"
          }
          ```
      tags:
        - Backup Policy
    delete:
      summary: Xóa policy
      operationId: delete-policies-policy_id
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
      description: |
        Policy chỉ được xóa khi:
          - Không được apply vào directory
          - Không có Recovery Point được tạo bởi policy
      tags:
        - Backup Policy
  '/dashboard/policies/{policy_id}/directories':
    parameters:
      - schema:
          type: string
        name: policy_id
        in: path
        required: true
    get:
      summary: Lấy danh sách direcory đang aplly policy id này
      tags:
        - Backup Policy
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/PolicyBackupDirectories.v1.yaml
              examples:
                example-1:
                  value:
                    backup-directories:
                      - e0a69ae7-fada-4426-beca-704f67e6d46c
                    created_at: '2020-06-13T11:48:12.554686'
                    id: c56b623c-385a-4a9d-834f-7364ffaf00ac
                    name: full backup
                    retention_days: null
                    retention_months: null
                    retention_weeks: null
                    schedule_pattern: '* * * *'
                    tenant_id: 98dbba57-60c7-4c22-8087-8313997ea776
                    updated_at: '2020-06-16T16:1'
      operationId: get-policies-policy_id-directories
  '/dashboard/machines/{machine_id}/directories/{backup_directory_id}/recovery-points':
    parameters:
      - schema:
          type: string
        name: machine_id
        in: path
        required: true
      - schema:
          type: string
        name: backup_directory_id
        in: path
        required: true
    get:
      summary: Lấy danh sách Recovery Point của 1 directory
      tags:
        - Recovery Point
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/RecoveryPoint.v1.yaml
        '':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/RecoveryPoint.v1.yaml
      operationId: get-machines-machine_id-directories-backup_directory_id-recovery-points
  '/dashboard/recovery-points/{recovery-point-id}/files':
    parameters:
      - schema:
          type: string
        name: recovery-point-id
        in: path
        required: true
    get:
      summary: Lấy danh sách Files của 1 Recovery Point
      tags:
        - Recovery Point
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/File.v1.yaml
      operationId: get-machines-machine_id-directories-backup_directory_id-recovery-points-recovery-point-id-files
      description: ''
  '/dashboard/machines/{machine_id}/directories/{backup_directory_id}/action':
    parameters:
      - schema:
          type: string
        name: machine_id
        in: path
        required: true
      - schema:
          type: string
        name: backup_directory_id
        in: path
        required: true
    post:
      summary: active/deactive backup directory
      operationId: post-dashboard-machines-machine_id-directories-backup_directory_id-action
      responses:
        '200':
          description: OK
      description: |-
        Thực hiện các action cho backup directory:
        - active/deactive
        - backup manual
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
        description: "Request body gồm có action\ncác action bao gồm:\n- active\n- deactive\n\n```\n{\n\t\"action\": \"deactive\",\n}\n```\n\n- backup_manual: Backup manual phai co them storage_type\n\n```\n{\n\t\"action\": \"backup_manual\",\n\t\"storage_type\": \"S3\",\n\t\"name\": <name-recovery-point-for-backup-manual>\n}\n```\n"
      tags:
        - BackupDirectory
  '/dashboard/recovery-points/{recovery-point-id}/action':
    parameters:
      - schema:
          type: string
        name: recovery-point-id
        in: path
        required: true
    post:
      summary: Action in recovery point
      operationId: post-dashboard-machines-machine_id-directories-backup_directory_id-recovery-points-recovery-point-id-action
      responses:
        '200':
          description: OK
      description: 'Action: restore to directory'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
        description: |-
          machine_id là máy đích mà muốn restore vào và path là đường dẫn của thư mục muốn restore

          ```
          {
              "machine_id": <id>,
              "path": "/path/to/directory"
          }
          ```
      tags:
        - Recovery Point
  '/dashboard/policies/{policy_id}/action':
    parameters:
      - schema:
          type: string
        name: policy_id
        in: path
        required: true
    post:
      summary: Apply/Unapply policy cho backup directory
      operationId: post-dashboard-policies-policy_id-action
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
        description: |-
          Request body chứa action:

          apply cho backup directory
          ```
          {
            "action": "apply_directory",
            "directory_id": "e0a69ae7-fada-4426-beca-704f67e6d46c"
          }
          ```
          unapply

          ```
          {
            "action": "unapply_directory",
            "directory_id": "e0a69ae7-fada-4426-beca-704f67e6d46c"
          }
          ```
      tags:
        - Backup Policy
  '/dashboard/machines/{machine_id}/directories/action':
    parameters:
      - schema:
          type: string
        name: machine_id
        in: path
        required: true
    post:
      summary: Active/Deactive nhiều directories đồng thời
      operationId: post-dashboard-machines-machine_id-directories-action
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              examples:
                active-1:
                  value:
                    message: Active multiple backup directory success
                active-2:
                  value:
                    message: Not have directory to active
                deactive-1:
                  value:
                    message: Deactive multiple backup directory success
                deactive-2:
                  value:
                    message: Not have directory to deactive
        '400':
          description: Bad Request
      description: Active/Deactive nhiều directories đồng thời
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                action:
                  type: string
                  enum:
                    - active
                    - deactive
                  example: active
                backup_directories:
                  type: array
                  description: List id backup-directories not empty
                  items:
                    type: string
                    format: uuid
              required:
                - action
                - backup_directories
            examples:
              active:
                value:
                  action: active
                  backup_directories:
                    - 3d08f398-47e8-417b-bf7d-47a62f00f2fa
                    - ad8d199f-c7e8-4ec7-b060-e813da36e32c
              deactive:
                value:
                  action: deactive
                  backup_directories:
                    - 3d08f398-47e8-417b-bf7d-47a62f00f2fa
                    - ad8d199f-c7e8-4ec7-b060-e813da36e32c
      tags:
        - BackupDirectory
    delete:
      summary: Xóa nhiều directories đồng thời
      operationId: delete-dashboard-machines-machine_id-directories-action
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '404':
          description: Not Found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                backup_directories:
                  type: array
                  description: List id backup-directories not empty
                  items:
                    type: string
                    format: uuid
                keep:
                  type: boolean
              required:
                - backup_directories
                - keep
      tags:
        - BackupDirectory
  '/dashboard/machines/{machine_id}/action':
    parameters:
      - schema:
          type: string
        name: machine_id
        in: path
        required: true
    post:
      summary: Enable/disable machine
      operationId: post-dashboard-machines-machine_id-action
      responses:
        '200':
          description: OK
      description: |-
        Endpoint thực hiện enable/disable machine

        - enable: enable lại tất cả directory của machine
        - disable: disable tất cả directory của machine

        Required request body action: enable/disable

        ```
        {
          "action": "enable"
        }
        ```
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                ation:
                  type: string
                  enum:
                    - enable
                    - disable
            examples:
              enable:
                value:
                  action: enable
              disable:
                value:
                  action: disable
      tags:
        - Machines
  '/dashboard/machines/{machine_id}/reset-secret-key':
    parameters:
      - schema:
          type: string
        name: machine_id
        in: path
        required: true
    post:
      summary: Reset secret key for machine
      operationId: post-dashboard-machines-machine_id-reset-secret-key
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/MachinePost.v1.yaml
      description: ''
      tags:
        - Machines
  /dashboard/recovery-points:
    get:
      summary: Lấy danh sách RecoveryPoint của tenant
      tags:
        - Recovery Point
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/RecoveryPoint.v1.yaml
      operationId: get-dashboard-recovery-points
      description: |-
        Trả về 1 list các recovery point của tenant, chứa đầy đủ thông tin về backup-directory và machine

        ```
        [
          {
            "backup_directory": {
              "activated": true,
              "created_at": "2020-08-26T15:27:45.174584+07:00",
              "deleted": true,
              "description": null,
              "id": "93f2ae07-b7ad-4fe7-8f8b-08d0831b73bd",
              "machine": {
                "agent_version": null,
                "created_at": "2020-08-26T14:42:44.122828+07:00",
                "deleted": true,
                "encryption": false,
                "host_name": null,
                "id": "90f59741-060b-4381-8ad6-f56117f3d2ee",
                "ip_address": null,
                "name": null,
                "os_machine_id": null,
                "os_version": null,
                "status": "OFFLINE",
                "tenant_id": "97ef441a-3edf-4ab7-847a-7afe17964e8f",
                "updated_at": "2020-09-10T16:50:31.635576+07:00"
              },
              "name": null,
              "path": "var/as/henlib/dev/nginx",
              "quota": null,
              "size": 0,
              "updated_at": "2020-09-10T16:50:31.594500+07:00"
            },
            "created_at": "2020-09-10T16:49:01.900761+07:00",
            "id": "8df81afc-88ec-4960-9c40-944bb6f3ca65",
            "name": "20/22/5",
            "recovery_point_type": "INITIAL_REPLICA",
            "status": "CREATED",
            "updated_at": "2020-09-10T16:49:01.900761+07:00"
          }
        ]
        ```
  '/dashborad/machines/{machined_id}/recovery-points':
    parameters:
      - schema:
          type: string
        name: machined_id
        in: path
        required: true
    get:
      summary: Lấy danh sách RecoveryPoint của machine
      tags:
        - Recovery Point
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
      operationId: get-dashborad-machines-machined_id-recovery-points
      description: |-
        Trả về 1 list các recovery point trong machine, chứa đầy đủ thông tin về backup-directory và machine

        ```
        [
          {
            "backup_directory": {
              "activated": true,
              "created_at": "2020-08-26T15:27:45.174584+07:00",
              "deleted": true,
              "description": null,
              "id": "93f2ae07-b7ad-4fe7-8f8b-08d0831b73bd",
              "machine": {
                "agent_version": null,
                "created_at": "2020-08-26T14:42:44.122828+07:00",
                "deleted": true,
                "encryption": false,
                "host_name": null,
                "id": "90f59741-060b-4381-8ad6-f56117f3d2ee",
                "ip_address": null,
                "name": null,
                "os_machine_id": null,
                "os_version": null,
                "status": "OFFLINE",
                "tenant_id": "97ef441a-3edf-4ab7-847a-7afe17964e8f",
                "updated_at": "2020-09-10T16:50:31.635576+07:00"
              },
              "name": null,
              "path": "var/as/henlib/dev/nginx",
              "quota": null,
              "size": 0,
              "updated_at": "2020-09-10T16:50:31.594500+07:00"
            },
            "created_at": "2020-09-10T16:49:01.900761+07:00",
            "id": "8df81afc-88ec-4960-9c40-944bb6f3ca65",
            "name": "20/22/5",
            "recovery_point_type": "INITIAL_REPLICA",
            "status": "CREATED",
            "updated_at": "2020-09-10T16:49:01.900761+07:00"
          }
        ]
        ```
  '/dashboard/recovery-ponits/{recovery_ponit_id}':
    parameters:
      - schema:
          type: string
        name: recovery_ponit_id
        in: path
        required: true
    get:
      summary: lấy thông tin chi tiết recovery point theo id
      tags:
        - Recovery Point
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
      operationId: get-dashboard-recovery-ponits-recovery_ponit_id
      description: |-
        lấy thông tin chi tiết recovery point theo id

        ```
        {
            "backup_directory": {
              "activated": true,
              "created_at": "2020-08-26T15:27:45.174584+07:00",
              "deleted": true,
              "description": null,
              "id": "93f2ae07-b7ad-4fe7-8f8b-08d0831b73bd",
              "machine": {
                "agent_version": null,
                "created_at": "2020-08-26T14:42:44.122828+07:00",
                "deleted": true,
                "encryption": false,
                "host_name": null,
                "id": "90f59741-060b-4381-8ad6-f56117f3d2ee",
                "ip_address": null,
                "name": null,
                "os_machine_id": null,
                "os_version": null,
                "status": "OFFLINE",
                "tenant_id": "97ef441a-3edf-4ab7-847a-7afe17964e8f",
                "updated_at": "2020-09-10T16:50:31.635576+07:00"
              },
              "name": null,
              "path": "var/as/henlib/dev/nginx",
              "quota": null,
              "size": 0,
              "updated_at": "2020-09-10T16:50:31.594500+07:00"
            },
            "created_at": "2020-09-10T16:49:01.900761+07:00",
            "id": "8df81afc-88ec-4960-9c40-944bb6f3ca65",
            "name": "20/22/5",
            "recovery_point_type": "INITIAL_REPLICA",
            "status": "CREATED",
            "updated_at": "2020-09-10T16:49:01.900761+07:00"
        }
        ```
    delete:
      summary: Xóa Recovery Point
      operationId: delete-dashboard-recovery-ponits-recovery_ponit_id
      responses:
        '200':
          description: OK
      tags:
        - Recovery Point
components:
  schemas: {}
  securitySchemes:
    X-Auth-Token:
      name: API Key
      type: apiKey
      in: header
      description: Token để xác thực với keystone
    X-Tenant-Name:
      name: API Key
      type: apiKey
      in: header
      description: Tenant name trong keystone
security:
  - X-Auth-Token: []
  - X-Tenant-Name: []
